# Generated by Django 3.2.7 on 2021-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20211104_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
