# Generated by Django 3.2.7 on 2021-11-30 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
