# Generated by Django 3.2.7 on 2021-12-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
